"""
vektor_pdf.py
Branded PDF report generator for Vektor Signals.
Call generate_pdf(prices, signals, date_label, tier) -> filepath
"""

import os
from datetime import datetime, timezone
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame,
    Paragraph, Spacer, Table, TableStyle, HRFlowable
)

# ── Colour palette ──────────────────────────────────────────────────────────
DARK_BG    = colors.HexColor('#0A0E1A')
PANEL_BG   = colors.HexColor('#111827')
CARD_BG    = colors.HexColor('#1A2235')
ELECTRIC   = colors.HexColor('#00F0FF')
GOLD       = colors.HexColor('#FFD700')
GREEN      = colors.HexColor('#00FF88')
RED        = colors.HexColor('#FF4444')
AMBER      = colors.HexColor('#FFA500')
PURPLE     = colors.HexColor('#9B59FF')
WHITE      = colors.HexColor('#FFFFFF')
LIGHT_GREY = colors.HexColor('#A0AEC0')
MID_GREY   = colors.HexColor('#4A5568')

W, H = A4

TIER_LABELS = {
    "starter": "STARTER",
    "pro":     "PRO",
    "vip":     "ELITE VIP",
}
TIER_COLORS = {
    "starter": colors.HexColor('#4DC3FF'),
    "pro":     colors.HexColor('#7B2FBE'),
    "vip":     GOLD,
}

BIAS_COLORS = {
    "ACCUMULATE":  GREEN,
    "STRONG BUY":  GREEN,
    "BUY":         GREEN,
    "HOLD":        AMBER,
    "WAIT":        AMBER,
    "CAUTION":     AMBER,
    "AVOID":       RED,
    "SELL":        RED,
    "REDUCE":      RED,
}

def _bias_color(bias):
    bias_upper = (bias or "").upper()
    for k, v in BIAS_COLORS.items():
        if k in bias_upper:
            return v
    return LIGHT_GREY

def _dark_background(canvas, doc, date_label, tier):
    canvas.saveState()
    # Full dark background
    canvas.setFillColor(DARK_BG)
    canvas.rect(0, 0, W, H, fill=1, stroke=0)

    # Top accent bar
    canvas.setFillColor(ELECTRIC)
    canvas.rect(0, H - 6, W, 6, fill=1, stroke=0)

    # Left side glow strip
    canvas.setFillColor(colors.HexColor('#001F3F'))
    canvas.rect(0, 0, 4, H, fill=1, stroke=0)

    # Footer bar
    canvas.setFillColor(PANEL_BG)
    canvas.rect(0, 0, W, 22*mm, fill=1, stroke=0)
    canvas.setFillColor(ELECTRIC)
    canvas.rect(0, 22*mm, W, 1, fill=1, stroke=0)

    # Footer text
    tier_label = TIER_LABELS.get(tier, "VIP")
    canvas.setFillColor(LIGHT_GREY)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(15*mm, 14*mm,
        f"VEKTOR SIGNALS {tier_label}  |  vektorsignals.com  |  {date_label}")
    canvas.drawRightString(W - 15*mm, 14*mm,
        "Not financial advice. For informational purposes only. DYOR.")
    canvas.setFillColor(MID_GREY)
    canvas.drawString(15*mm, 9*mm,
        "Intelligence report generated by SENTINEL AI System")

    canvas.restoreState()


def _styles():
    return {
        'title': ParagraphStyle('title',
            fontName='Helvetica-Bold', fontSize=24,
            textColor=WHITE, alignment=TA_LEFT, spaceAfter=2),
        'subtitle': ParagraphStyle('subtitle',
            fontName='Helvetica', fontSize=9,
            textColor=ELECTRIC, alignment=TA_LEFT, spaceAfter=4, leading=13),
        'section': ParagraphStyle('section',
            fontName='Helvetica-Bold', fontSize=11,
            textColor=ELECTRIC, alignment=TA_LEFT, spaceBefore=10, spaceAfter=4),
        'body': ParagraphStyle('body',
            fontName='Helvetica', fontSize=8.5,
            textColor=LIGHT_GREY, alignment=TA_LEFT, leading=13, spaceAfter=4),
        'highlight': ParagraphStyle('highlight',
            fontName='Helvetica-Bold', fontSize=8.5,
            textColor=WHITE, alignment=TA_LEFT, leading=13, spaceAfter=4),
        'key_levels': ParagraphStyle('key_levels',
            fontName='Helvetica-Oblique', fontSize=8,
            textColor=ELECTRIC, alignment=TA_LEFT, spaceAfter=6),
        'small_grey': ParagraphStyle('small_grey',
            fontName='Helvetica', fontSize=8,
            textColor=LIGHT_GREY, alignment=TA_LEFT, leading=12),
    }


def _divider(color=ELECTRIC, thickness=0.5):
    return HRFlowable(width='100%', thickness=thickness,
                      color=color, spaceAfter=5, spaceBefore=2)


def _asset_block(ticker, price_data, sig_data, S):
    """Returns a list of flowables for one asset."""
    items = []

    price     = price_data.get('price', 0)
    change    = price_data.get('change', 0)
    bias      = sig_data.get('bias', '')
    ta        = sig_data.get('ta', '')
    catalyst  = sig_data.get('catalyst', '')
    summary   = sig_data.get('summary_line', '')
    entry     = sig_data.get('entry_zone', '—')
    t1        = sig_data.get('target_1', '—')
    t2        = sig_data.get('target_2', '—')
    sl        = sig_data.get('stop_loss', '—')
    rsi       = sig_data.get('rsi_estimate', '—')
    structure = sig_data.get('structure', '—')

    chg_color = '#00FF88' if change >= 0 else '#FF4444'
    chg_str   = f"+{change:.1f}%" if change >= 0 else f"{change:.1f}%"
    bias_col  = _bias_color(bias)

    # Header row — asset name + price
    header = Table([[
        Paragraph(f'<b>{ticker}</b>',
            ParagraphStyle('ah', fontName='Helvetica-Bold', fontSize=11, textColor=GOLD)),
        Paragraph(
            f'<font color="#FFFFFF">${price:,.2f}</font>  '
            f'<font color="{chg_color}">{chg_str}</font>',
            ParagraphStyle('ap', fontName='Helvetica-Bold', fontSize=10,
                           textColor=WHITE, alignment=TA_RIGHT)),
    ]], colWidths=[120*mm, 60*mm],
    style=[('BACKGROUND', (0,0), (-1,-1), PANEL_BG),
           ('TOPPADDING', (0,0), (-1,-1), 5),
           ('BOTTOMPADDING', (0,0), (-1,-1), 5),
           ('LEFTPADDING', (0,0), (-1,-1), 8),
           ('RIGHTPADDING', (0,0), (-1,-1), 8)])
    items.append(header)

    # Signal badge
    sig_table = Table([[
        Paragraph(f'SIGNAL: {bias}',
            ParagraphStyle('sig', fontName='Helvetica-Bold', fontSize=8.5,
                           textColor=bias_col)),
        Paragraph(f'RSI ~{rsi}  |  Structure: {structure}',
            ParagraphStyle('rsi', fontName='Helvetica', fontSize=8,
                           textColor=LIGHT_GREY, alignment=TA_RIGHT)),
    ]], colWidths=[100*mm, 80*mm],
    style=[('BACKGROUND', (0,0), (-1,-1), CARD_BG),
           ('TOPPADDING', (0,0), (-1,-1), 4),
           ('BOTTOMPADDING', (0,0), (-1,-1), 4),
           ('LEFTPADDING', (0,0), (-1,-1), 8),
           ('RIGHTPADDING', (0,0), (-1,-1), 8)])
    items.append(sig_table)

    # TA + Catalyst
    if ta:
        items.append(Paragraph(ta, S['body']))
    if catalyst:
        items.append(Paragraph(catalyst, S['body']))

    # Trade levels table
    levels = Table([
        [Paragraph('ENTRY ZONE', ParagraphStyle('lh', fontName='Helvetica-Bold', fontSize=7.5, textColor=AMBER)),
         Paragraph('TARGET 1', ParagraphStyle('lh', fontName='Helvetica-Bold', fontSize=7.5, textColor=GREEN)),
         Paragraph('TARGET 2', ParagraphStyle('lh', fontName='Helvetica-Bold', fontSize=7.5, textColor=GREEN)),
         Paragraph('STOP LOSS', ParagraphStyle('lh', fontName='Helvetica-Bold', fontSize=7.5, textColor=RED))],
        [Paragraph(entry, ParagraphStyle('lv', fontName='Helvetica-Bold', fontSize=8.5, textColor=WHITE)),
         Paragraph(t1,    ParagraphStyle('lv', fontName='Helvetica-Bold', fontSize=8.5, textColor=GREEN)),
         Paragraph(t2,    ParagraphStyle('lv', fontName='Helvetica-Bold', fontSize=8.5, textColor=GREEN)),
         Paragraph(sl,    ParagraphStyle('lv', fontName='Helvetica-Bold', fontSize=8.5, textColor=RED))],
    ], colWidths=[45*mm, 45*mm, 45*mm, 45*mm],
    style=[('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#0D1929')),
           ('TOPPADDING', (0,0), (-1,-1), 4),
           ('BOTTOMPADDING', (0,0), (-1,-1), 4),
           ('LEFTPADDING', (0,0), (-1,-1), 8),
           ('GRID', (0,0), (-1,-1), 0.3, MID_GREY)])
    items.append(levels)

    if summary:
        items.append(Paragraph(f'⚡ {summary}',
            ParagraphStyle('sum', fontName='Helvetica-Bold', fontSize=8.5,
                           textColor=ELECTRIC, leading=13, spaceBefore=4, spaceAfter=6)))

    items.append(Spacer(1, 3*mm))
    return items


def generate_pdf(prices, signals, date_label, tier='vip', output_dir='outputs'):
    """
    Generate branded Vektor Signals PDF.

    Args:
        prices  : dict  — {"BTC": {"price": 66457.0, "change": -2.1}, ...}
        signals : dict  — full Claude JSON response
        date_label: str — e.g. "Sunday 29 March 2026"
        tier    : str   — "starter" | "pro" | "vip"
        output_dir: str — folder to save PDF

    Returns:
        str — filepath of generated PDF
    """
    os.makedirs(output_dir, exist_ok=True)

    date_file = datetime.now(timezone.utc).strftime("%Y%m%d")
    filename  = os.path.join(output_dir, f"vektor_{tier}_{date_file}.pdf")

    tier_color = TIER_COLORS.get(tier, GOLD)
    tier_label = TIER_LABELS.get(tier, 'VIP')

    # Determine assets to include per tier
    tier_assets = {
        'starter': ['BTC', 'ETH', 'XRP'],
        'pro':     ['BTC', 'ETH', 'XRP', 'SOL', 'BNB', 'HYPE'],
        'vip':     ['BTC', 'ETH', 'XRP', 'SOL', 'BNB', 'HYPE'],
    }
    assets = tier_assets.get(tier, ['BTC', 'ETH', 'XRP', 'SOL', 'BNB', 'HYPE'])

    S = _styles()

    def page_background(canvas, doc):
        _dark_background(canvas, doc, date_label, tier)

    doc = BaseDocTemplate(
        filename, pagesize=A4,
        leftMargin=15*mm, rightMargin=15*mm,
        topMargin=16*mm, bottomMargin=28*mm
    )
    frame   = Frame(doc.leftMargin, doc.bottomMargin,
                    doc.width, doc.height, id='main')
    template = PageTemplate(id='dark', frames=frame, onPage=page_background)
    doc.addPageTemplates([template])

    story = []

    # ── HEADER ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 3*mm))

    header_row = Table([[
        Paragraph('⚡ VEKTOR SIGNALS',
            ParagraphStyle('ht', fontName='Helvetica-Bold', fontSize=22, textColor=WHITE)),
        Paragraph(tier_label,
            ParagraphStyle('tl', fontName='Helvetica-Bold', fontSize=11,
                           textColor=DARK_BG, alignment=TA_RIGHT)),
    ]], colWidths=[140*mm, 40*mm],
    style=[
        ('BACKGROUND', (0,0), (0,0), DARK_BG),
        ('BACKGROUND', (1,0), (1,0), tier_color),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (0,0), 0),
        ('LEFTPADDING', (1,0), (1,0), 6),
        ('RIGHTPADDING', (1,0), (1,0), 8),
    ])
    story.append(header_row)

    theme = signals.get('session_theme', 'Daily Intelligence Brief')
    story.append(Paragraph(
        f'DAILY INTELLIGENCE BRIEF  |  {date_label.upper()}  |  SENTINEL SYSTEM',
        S['subtitle']))
    story.append(_divider(ELECTRIC, 1))

    # ── SESSION THEME + MACRO ─────────────────────────────────────────────────
    macro = signals.get('macro_summary', '')
    theme_box = Table([[
        Paragraph(f'"{theme}"',
            ParagraphStyle('th', fontName='Helvetica-Bold', fontSize=11, textColor=GOLD)),
    ]], colWidths=[180*mm],
    style=[('BACKGROUND', (0,0), (-1,-1), PANEL_BG),
           ('TOPPADDING', (0,0), (-1,-1), 6),
           ('BOTTOMPADDING', (0,0), (-1,-1), 6),
           ('LEFTPADDING', (0,0), (-1,-1), 10)])
    story.append(theme_box)

    if macro:
        story.append(Paragraph(macro, S['highlight']))
    story.append(Spacer(1, 2*mm))
    story.append(_divider(MID_GREY))

    # ── ASSET SIGNALS ─────────────────────────────────────────────────────────
    story.append(Paragraph('📊  ASSET SIGNALS', S['section']))

    all_signals = signals.get('signals', {})
    for ticker in assets:
        price_data = prices.get(ticker, {'price': 0, 'change': 0})
        sig_data   = all_signals.get(ticker, {})
        story.extend(_asset_block(ticker, price_data, sig_data, S))

    story.append(_divider(MID_GREY))

    # ── POSITIONING SUMMARY TABLE ─────────────────────────────────────────────
    story.append(Paragraph('📋  POSITIONING SUMMARY', S['section']))

    hdr_style = ParagraphStyle('th', fontName='Helvetica-Bold', fontSize=8, textColor=ELECTRIC)
    pos_rows = [[
        Paragraph('ASSET', hdr_style),
        Paragraph('PRICE', hdr_style),
        Paragraph('SIGNAL', hdr_style),
        Paragraph('ENTRY ZONE', hdr_style),
        Paragraph('TARGET 1', hdr_style),
        Paragraph('STOP', hdr_style),
    ]]

    for ticker in assets:
        price_data = prices.get(ticker, {'price': 0, 'change': 0})
        sig_data   = all_signals.get(ticker, {})
        bias       = sig_data.get('bias', '—')
        bias_col   = _bias_color(bias)

        pos_rows.append([
            Paragraph(ticker,
                ParagraphStyle('td', fontName='Helvetica-Bold', fontSize=8, textColor=GOLD)),
            Paragraph(f"${price_data.get('price', 0):,.0f}",
                ParagraphStyle('td', fontName='Helvetica', fontSize=8, textColor=WHITE)),
            Paragraph(bias,
                ParagraphStyle('td', fontName='Helvetica-Bold', fontSize=8, textColor=bias_col)),
            Paragraph(sig_data.get('entry_zone', '—'),
                ParagraphStyle('td', fontName='Helvetica', fontSize=8, textColor=AMBER)),
            Paragraph(sig_data.get('target_1', '—'),
                ParagraphStyle('td', fontName='Helvetica', fontSize=8, textColor=GREEN)),
            Paragraph(sig_data.get('stop_loss', '—'),
                ParagraphStyle('td', fontName='Helvetica', fontSize=8, textColor=RED)),
        ])

    pos_table = Table(pos_rows,
        colWidths=[20*mm, 28*mm, 38*mm, 36*mm, 36*mm, 22*mm],
        style=[
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0D1929')),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [CARD_BG, PANEL_BG]),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('GRID', (0,0), (-1,-1), 0.3, MID_GREY),
        ])
    story.append(pos_table)
    story.append(Spacer(1, 6*mm))

    doc.build(story)
    print(f"  PDF generated: {filename}")
    return filename
